#!/usr/bin/env zsh

IRCPATH=${HOME}/utilities/irc
UPDATED_FILES=${IRCPATH}/updated.txt

function TRAPINT {
    cat < /dev/null > ${UPDATED_FILES}
}

while true; do
    clear
    query
    LC_ALL=C sort ${UPDATED_FILES}
    grep -E '^[^#]' ${UPDATED_FILES} &> /dev/null && printf '\x07'
    sleep 10
done
