#!/usr/bin/env zsh

IRCPATH=${HOME}/utilities/irc
IRCSHADOW=${HOME}/utilities/irc_shadow
UPDATED_FILES=${IRCPATH}/updated.txt

builtin cd ${IRCPATH}

if [[ ! -f ${UPDATED_FILES} ]]; then
    touch ${UPDATED_FILES}
fi

for i in $(find . -newer ${UPDATED_FILES} -name 'out'); do
    grep -Ev '&bitlbee' <<< ${i} &> /dev/null || continue

    re='^[<>][^<]*<cdchawthorne>|^[^<>]'
    [[ -f ${IRCSHADOW}/$i ]] && [[ -z "$(diff ${IRCPATH}/$i ${IRCSHADOW}/$i | grep -Ev ${re})" ]] && continue
    mkdir -p "$(dirname ${IRCSHADOW}/$i)"
    cp ${IRCPATH}/$i ${IRCSHADOW}/$i
    channel="$(sed -re 's_\./[^/]*/([^/]*)/out$_\1_' <<< $i)"
    grep -F ${channel} ${UPDATED_FILES} &> /dev/null || echo ${channel} >> ${UPDATED_FILES}
done
