#!/usr/bin/env zsh

#TODO: have this reference the currently available buddies in bitblee

if [[ $# -ne 1 ]]; then
    echo "usage: $0 NAME" 1>&2
    exit 1
fi

read_command='rlwrap sed -rue ''s_^/me (.*)$_\x01ACTION \1\x01_'' > in'
pager_command='tail -n +0 -f out | '
pager_command+='sed -rue ''^s_([^<]*)<([^>]*)> ACTION ([]*)$_'
pager_command+='\1* \2 \3_'''

(
    setopt no_nomatch
    builtin cd ~/utilities/irc/*/$1 &> /dev/null ||
        builtin cd ~/utilities/irc/*/$1* &> /dev/null ||
        {echo 'ERROR: no such directory' 1>&2; return 1}
    tmux new-window -t irc -n "$(basename ${PWD})" 'tail -n +0 -f out'
    tmux split-window -t "irc:$(basename ${PWD})" -l 1 ${read_command}
)
